### ISSUE TITLE
ImmMap adds same keys as separate key-values

### ISSUE THREAD

**Issue by Imunhatep** [phunkie/phunkie#18]
Not sure if this behavior is by design, since "promote()" used in keys returns objects.. But I would expect returning new instances of ImmMap with overwritten value instead of duplicated keys

**Comment by MarcelloDuarte** [comment]
That doesn't sound like intended behaviour. I am marking this as a bug. Internally ImmMap uses SPL ObjectStorage attach method. We probably need some manual verification of the key identity before promoting the key to the Integer or String object, to guarantee uniqueness.
