### ISSUE TITLE
bug in compose

### ISSUE THREAD

**Issue by prolic** [phunkie/phunkie#19]
```php
$pipe = compose(
    parseRequest,
    function (Request $request): Response {
        return new EmptyResponse(200);
    }
);
$pipe();
```

where `const parseRequest = 'HMC\Calculator\parseRequest';`.

This leads to first argument being a string and second being an object, thus the following error appears:

```
Uncaught TypeError: cannot combine values of different types. using Closure
```

Any possibility to avoid this?

**Comment by prolic** [comment]
Also combine doesn't work with string representing functions at all, because it just concats those strings.

**Comment by MarcelloDuarte** [comment]
Hi @prolic,

Regarding the first error, I cannot reproduce it. This code works for me (and prints "4").

```php
<?php

require_once "vendor/autoload.php";

use function Phunkie\Functions\function1\compose;

const parseRequest = "parseRequest";
function parseRequest($x) { return $x + 1; }

$pipe = compose(
    parseRequest,
    function($x) { return $x * 2; }
);

echo $pipe(1);
```

As per the second issue, this is a hard call to make as people may want to be combining strings and checking if they are callable seems a bit hacky. They should use compose if they want to combine callables. What do you think?

**Comment by MarcelloDuarte** [comment]
Hi @prolic,

any thoughts? What would you like me to do with this one?

Marcello

**Comment by prolic** [comment]
Sorry I've been quite busy these days. I will investigate once again and verify.

**Comment by prolic** [comment]
I can confirm it's working indeed, so most likely I had a weird typo I didn't see in the first place. Sorry for bothering.
