### ISSUE TITLE
Some::map called three times

### ISSUE THREAD

**Issue by OlexandrPopov** [phunkie/phunkie#22]
Consider the following code:

```php
/** @test */
public function mapCalledThreeTimes()
{
    $some = Some('test my map method');
    $some->map(function ($str) {
        $this->assertEquals('test my map method', $str);
        return true;
    });

    $this->assertEquals(3, Assert::getCount());
}
```

The assertion `$this->assertEquals('test my map method', $str);` is performed 3 times. Is that the desired behaviour?

**Comment by OlexandrPopov** [comment]
https://github.com/phunkie/phunkie/blob/8cfcd43bab48a4e10bd39ef1db6b9abf6af1c3e4/src/Phunkie/Ops/Option/OptionFunctorOps.php#L26

In the `\Phunkie\Ops\Option\OptionFunctorOps::map` method the result of the "map" function is compared to `None` and `null`. I'm not sure that comparison is needed at all but can it be optimized and called only once?

For example:

public function map(callable $f): Kind { switch (true) {
    case $this->isEmpty(): return None();
    case ($f($this->get()) instanceof None || $f($this->get()) === null): return None();
    default: return Some($f($this->get())); }
}

**Comment by MarcelloDuarte** [comment]
Hey, thanks for spotting that out! Fixed now.
